-- Create the 'faqs' table
CREATE TABLE public.faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create an index on the 'slug' column for faster lookups
CREATE INDEX idx_faqs_slug ON public.faqs (slug);

-- Enable Row Level Security (RLS) for the 'faqs' table
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;

-- Create RLS policy for public read access
CREATE POLICY "Public FAQs are viewable by everyone."
ON public.faqs FOR SELECT
USING (true);
